# This file is part of cjdk.
# Copyright 2022-25 Board of Regents of the University of Wisconsin System
# SPDX-License-Identifier: MIT

title: cjdk Documentation
author: Mark A. Tsuchida
copyright: "2022 Board of Regents of the University of Wisconsin System"

repository:
  url: https://github.com/cachedjdk/cjdk
  path_to_book: docs
  branch: main

html:
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true

sphinx:
  extra_extensions:
    - "sphinx.ext.autodoc"
    - "sphinx.ext.napoleon"
    - "sphinxcontrib.programoutput"

execute:
  execute_notebooks: cache
  run_in_temp: true
  timeout: 180
